<?php
/**
 * @file
 * Code for the nesi_slideshow feature.
 */

include_once 'nesi_slideshow.features.inc';

function nesi_slideshow_form_slideshow_item_node_form_alter(&$form, &$form_state, $form_id) {
  // Slides do not have a standard editable title
  $form['title']['#default_value'] = 'Slideshow Banner Item';
  $form['title']['#access'] = FALSE;
  $form['options']['promote']['#default_value'] = 0;
  $form['options']['sticky']['#default_value'] = 0;

  // Uncomment next line if no need for configuration tabs
  //$form['additional_settings']['#access'] = FALSE;

  // Hide menu config tab
  $form['menu']['#access'] = FALSE;
}

function nesi_slideshow_block_info() {    
  $blocks['nesi_slideshow'] = array(
    // info: The name of the block.
    'info' => t('NeSI Slideshow Banner'),
    'status' => TRUE,
    'region' => 'subheader',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'cache' => DRUPAL_NO_CACHE,
    'pages' => implode("\n",array('<front>')),
  );

  return $blocks;
}

function nesi_slideshow_block_view($delta = '') {

  $block = array();
  // Load content
  $view = views_get_view('nesi_slideshow');
  $view->execute();
  $response = $view->result; 
  //init  
  $slides = '';
  $count = 0;

  if (!empty($response)) {
    foreach ($response as $slide) {
      // Get image
      $url = file_create_url($slide->field_field_ns_banner_image[0]['rendered']['#item']['uri']);
      $url = parse_url($url);
      // Set active item
      $active = empty($count);  
      // Prep content variables
      $variables = array(
        'banner_bg_color' => $slide->field_field_ns_banner_bg_color[0]['rendered']['#item'], 
        'primary_bg_color' => $slide->field_field_ns_primary_bg_color[0]['rendered']['#item'], 
        'secondary_bg_color' => $slide->field_field_ns_secondary_bg_color[0]['rendered']['#item'], 
        'primary_title' => $slide->field_field_ns_title_primary[0]['rendered']['#markup'],
        'secondary_title' => $slide->field_field_ns_title_secondary[0]['rendered']['#markup'],
        'secondary_title_line_2' => $slide->field_field_secondary_title_line_2[0]['rendered']['#markup'],
        'link_title' => $slide->field_field_ns_link_title[0]['rendered']['#markup'],
        'link_target' => url($slide->field_field_ns_link_target_node[0]['rendered']['#href']),
        'link_color' => $slide->field_field_ns_link_color[0]['rendered']['#item'],
        'image_path' => $url['path'],
        'active' => $active,
      );
      $slides .= theme('nesi_slideshow_item', $variables);
      $count++;
    } 
  }
  else {
    // Use defaults if no slides
    $slides = theme('nesi_slideshow_item', array('active' => TRUE));
  }
  // The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'nesi_slideshow':
      // Set block content
      $block['subject'] = NULL;
      $block['content'] = theme('nesi_slideshow_wrapper', array('content' => $slides));
      break;
  }
  
  return $block;
}

function nesi_slideshow_theme($existing, $type, $theme, $path) {
  
  $variables = array(
    'banner_bg_color' => 'E1E1E1', 
    'primary_bg_color' => '000000', 
    'secondary_bg_color' => '000000', 
    'primary_title' => 'No slides published?',
    'secondary_title' => NULL,
    'link_title' => NULL,
    'link_target' => '#',
    'link_color' => 'FFFFFF',
    'image_path' => NULL,
    'active' => FALSE,
  );

  return array(
    'nesi_slideshow_item' => array(
      'variables' => $variables,
      'template' => 'nesi-slideshow-item', 
      'path' => drupal_get_path('module', 'nesi_slideshow') .'/templates'
    ),
    'nesi_slideshow_wrapper' => array(
      'variables' => array('content' => NULL),
      'template' => 'nesi-slideshow-wrapper', 
      'path' => drupal_get_path('module', 'nesi_slideshow') .'/templates'
    )
  );  
}
