<?php
/**
 * @file
 * NeSI Portal module.
 * 
 * The purpose of this module is to provide configuration and settings for the NeSI portal.
 * The module may be removed as the build process is further developed. 
 *
 */

function nesi_portal_block_info() {    
  $blocks['researcher_navigation'] = array(
    // info: The name of the block.
    'info' => t('Researcher Navigation'),
    'status' => TRUE,
    'region' => 'sidebar_second',
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'cache' => DRUPAL_NO_CACHE,

  );

  return $blocks;
}

function nesi_portal_block_view($delta = '') {
  global $base_url;
  global $user;
  $block = array();

  // Check if user has a current proposal mmmkay.. cause we only want 1 open at a time
  $view = views_get_view('researcher_my_proposals');
  $view->execute();
  $response = $view->result; 
  
  $current_proposal_link = '[cpl_access]'; 
  if (!empty($response)) {
    // Need to get link to the exact proposal for this user...
    if (!empty($response[0]->nid)) { 
      $current_proposal_link = '<li class="collapsed"><a href="'.$base_url.'/node/'.$response[0]->nid.'">Current Proposal</a></li>';
    }
  }
  else {
    $current_proposal_link = '<li class="collapsed"><a href="'.$base_url.'/researcher/proposal/add">Add Proposal</a></li>';
  }

  // The $delta parameter tells us which block is being requested.
    switch ($delta) {
      case 'researcher_navigation':
        // Create your block content here
        if ($user->uid <> 0) {
        $block['subject'] = t('Researcher menu');
        $block['content'] = '<ul class="menu nav">
            <li class="first leaf"><a title="Dashboard" href="'.$base_url.'/user/dashboard">Proposals</a></li>
            <!--<li class="first leaf"><a title="Project History" href="'.$base_url.'/researcher/history">History</a></li>-->
            <!--<li class="leaf"><a title="Live Projects" href="'.$base_url.'/researcher/projects">Live Projects</a></li>-->
            <!--'.$current_proposal_link.'-->
            <li class="leaf"><a href="'.$base_url.'/hpc-calculator">HPC Calculator</a></li>
            <li class="leaf"><a href="'.$base_url.'/user">My Account</a></li>
            <li class="last leaf"><a href="'.$base_url.'/user/logout">Logout</a></li>
            </ul>';
        }
        break;
    }
  
  return $block;
}

