<?php
/**
 * @file
 * NeSI Config module.
 * 
 * @todo Provide config interface in admin.
 */

/**
 * Implements hook_menu().
 */
function nesi_config_menu() {

  #Menu disabled until admin override options provided.
  $items['admin/config/nesi/website'] = array(
    'title' => 'NeSI Website Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nesi_config_admin_settings'),
    'access arguments' => array('nesi website config'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'nesi_config.admin.inc'
  );

  return $items;
}

function nesi_config_permission() {

  return array(
      'nesi website config' => array(
          'title' => 'Nesi config',
          'description' => t('A description'),
        ),
    );
}
  
function nesi_config_wysiwyg_editor_settings_alter(&$settings, $context) {
  
  if ($context['profile']->editor == 'ckeditor') {
    // enable show blocks option by default on startup
    $settings['startupOutlineBlocks'] = true;
  }
}

/**
* Implements hook_block_info().
*/
function nesi_config_block_info() {
  $blocks['nesi_faq'] = array(
    'info'   => t('Application page FAQ'),
    'status' => TRUE,
    'region' => 'content',
    'weight'    => 0,
    'visibility' => 1,
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function nesi_config_block_view($delta = '') {

  switch ($delta) {
    case 'nesi_faq':
      $block['subject'] = t('Frequently Asked Questions: "See <a href="https://support.nesi.org.nz/">Support</a> for more details"');
      $block['content'] = nesi_faq_content();
      return $block;
    break;
  }
}

function nesi_faq_content() {

  $faqs = variable_get('nesi_faqs');

  $i = 0;
  foreach ( $faqs as $faq ) {
    $content .= '<div class="faq"><h4>' . $faq['question'] . '</h4><p>' . $faq['answer'] . '</p></div>';
    $i++;
  }

  return $content;
}
