<?php
/**
 * @file
 * NeSI Slideshow module - installation.
 * 
 * This file is executed on installation of the nesi_slideshow module.
 *
 */

/**
 * Implements hook_install()
 */
function nesi_slideshow_install() {

  /* Current actions on install:
   * Set URI pattern for slideshow
   */

  /* Set default URI pattern */
  variable_set( 'pathauto_node_slideshow_item_pattern', 'banner/[node:nid]' );

}
