<?php

/**
* Implements hook_block_info().
*/
function nesi_user_modal_block_info() {
  $blocks = array();
  $blocks['nesi-user-modal-login'] = array(
    'info' => t('NeSI User Login/Register Menu'),
    'status' => TRUE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => '',
  );

  $blocks['nesi-user-modal-edit-profile'] = array(
    'info' => t('NeSI User Edit Profile'),
    'status' => TRUE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => '',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function nesi_user_modal_block_view($delta = '') {
  switch ($delta) {
    case 'nesi-user-modal-login':
      return user_is_logged_in() ? _nesi_user_modal_logged_in_block_view() : _nesi_user_modal_login_block_view();
  }
  return NULL;
}

/**
* Implements hook_form_alter().
*/
function nesi_user_modal_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_login':
    case 'user_register_form':
      // Add ajax wrapper to form.
      $html_id = str_replace('_', '-', $form_id);
      $form['#prefix'] = '<div id="ajax-' . $html_id . '-wrapper">';
      $form['#suffix'] = '</div>';
      // Add ajax functionality to form submit button.
      $form['actions']['submit']['#ajax'] = array(
        'callback' => '_nesi_user_modal_ajax_callback',
        'wrapper' => 'ajax-' . $html_id . '-wrapper',
        'event' => 'click',
      );
      break;
  }
}

function _nesi_user_modal_ajax_callback($form, $form_state) {
  ctools_include('ajax');
  ctools_add_js('ajax-responder');

  if (form_get_errors()) {
    return $form; // Reload form if it didn't pass validation.
  }

  if ($form['#id'] === 'user-login') {
    drupal_set_message(check_plain('Successful login'));
  }

  $commands = array();
  $commands[] = ctools_ajax_command_reload();
  return array(
    '#type' => 'ajax',
    '#commands' => $commands
  );
}

function _nesi_user_modal_login_block_view() {
  global $base_url;
  $asset_path = drupal_get_path('theme', variable_get('theme_default', NULL));

  $content = '<ul class="nav pull-right">';
  $content .= '<li>';
  $content .= '<a href="user/login" role="button" data-toggle="modal" data-target="#nesiLoginModal" data-remote="false">' . t('Login') . '</a>';
  $content .= '<div id="nesiLoginModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="nesiLoginModalLabel" aria-hidden="true">

  <div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  </div>
    <div class="modal-body">
          <div class="pull-left login-via-tuakiri">
            <div>
            <h2>Login using your institutions credentials</h2>
            <div class="tuakiri">
              <p>We allow students, academics, alumni and researchers to get secure and seamless access to our computer resources using one set of credentials granted by their home organisation.</p>
              <img alt="Logos" src="/'.$asset_path.'/assets/img/uni-logos.gif">
              <p><a class="btn" href="'.shib_auth_generate_login_url().'">Log in</a></p>
            </div>
            </div>
          </div>
          <div class="pull-right login-via-drupal">
            <h2>Login using NeSI Account</h2>
              ' . drupal_render(drupal_get_form('user_login')) . '
          </div>
    </div>
    <div class="modal-footer">
      <div class="pull-left">or <a class="nesi-register-link" href="/user/register">click here to register</a> for a NeSI account.</div>
    </div>
  </div>
 ';

  $content .= '</li>';
  $content .= '</ul>';

  return array(
    'subject' => NULL,
    'content' => $content,
  );
}

function _nesi_user_modal_logged_in_block_view() {
  global $base_url;
  global $user;
  $user_data = $user;
  $asset_path = drupal_get_path('theme', variable_get('theme_default', NULL));

  $content = '<ul class="nav pull-right">';
  $content .= '<li>';
  $content .= '<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-target="#">' . format_username($user_data) . '</a>';
      $dropdown_menu = menu_tree_all_data('user-menu');
      $output_menu = menu_tree_output($dropdown_menu);
      $sub_menu = drupal_render($output_menu);
  $content .= $sub_menu;
  $content .= '</li>';
  $content .= '</ul>';

  return array(
    'subject' => NULL,
    'content' => $content,
  );
}

