<?php
/**
 * @file
 * NeSI User module.
 * 
 * The purpose of this module is to provide additional functionality for user registration 
 * and user update events within the NeSI portal. This module communicates with the NeSI
 * REST API to ensure user data is kept up to date within the NeSI account system.
 *
 * @todo Add terms of service
 */

include_once 'nesi_user.features.inc';


/**
 * Implements hook_init()
 */
function nesi_user_init(){
 
  // Implement check to see if user has setup a researcher_profile
  // This check is done for users created automatically by Tuakiri or other external 
  // process where a researcher profile will not have been assigned by default

  global $user;

  if($user->uid && $user->uid != 1){

    $account = user_load($user->uid);
    //$obj = entity_metadata_wrapper('user', $account);
    //dpm($obj->getPropertyInfo());
    $profile = profile2_load_by_user($account->uid);
    //dpm($profile);
    $destination = drupal_get_destination();

    if(empty( $profile['researcher_profile']->pid )){

      if($destination['destination'] != 'user/'.$account->uid.'/edit/researcher_profile' && $destination['destination'] != 'user/logout'){
        drupal_set_message('Researcher profile incomplete.', 'error');
        drupal_set_message('Please ensure that you complete your researcher profile below.', 'error');
        drupal_goto('user/'.$account->uid.'/edit/researcher_profile');
      }
    }
  }
}

/**
 * Implements hook_form_profile2_form_alter()
 */
function nesi_user_form_profile2_form_alter(&$form, &$form_state) {
  //drupal_set_message(print_r($form['profile_researcher_profile']['field_user_nationality'][LANGUAGE_NONE]['#options'], TRUE));  // print array to messages
  //drupal_set_message(print_r($form['profile_researcher_profile'], TRUE));  // print array to messages

  // User Registration form alter
  if ($form['#form_id'] == 'user_register_form') {
    $queue = $form['profile_researcher_profile']['field_user_nationality'][LANGUAGE_NONE]['#options'];

    // Provide New Zealand and Australia as a primary option in nationality field.
    $new_option = new stdClass();
    $new_option->option['Select Nationality'] = array('NZ' => 'New Zealand', 'AU' => 'Australia'); 

    $cur_option = new stdClass();
    $cur_option->option['All Countries'] = $queue; 

    $form['profile_researcher_profile']['field_user_nationality'][LANGUAGE_NONE]['#default_value'] = '_none';
    $form['profile_researcher_profile']['field_user_nationality'][LANGUAGE_NONE]['#options'] = array($new_option, $cur_option);
    //dpm($form['profile_researcher_profile']['field_user_nationality']);
  }

  // User Profile form alter
  if ($form['#form_id'] == 'user_profile_form') {
    
    // Check user
    global $user;
    dpm($user);
     
    if ($user->uid > 1) {
      // Get user data from GOLD
      $rest_user_id = 'tuakiri-test-hash-'.$user->uid;
      $rest_result = nesi_rest_get_user($rest_user_id);  
      
      // Check for error or http response
      if ($rest_result <> FALSE) {
        dpm('User was successfully retrieved from GOLD.');
        dpm($rest_result);
        // Display nesi_rest data instead of Drupal data... (GOLD is considered "up to date")
        
        // Convert from json
        $user_data = json_decode($rest_result['json_data']);
        
        if ($user_data) {
          dpm($user_data);
          $form['profile_researcher_profile']['field_user_firstname'][LANGUAGE_NONE][0]['value']['#default_value'] = $user_data->firstName;
          $form['profile_researcher_profile']['field_user_middlename'][LANGUAGE_NONE][0]['value']['#default_value'] = $user_data->middleName;
          $form['profile_researcher_profile']['field_user_lastname'][LANGUAGE_NONE][0]['value']['#default_value'] = $user_data->lastName;
          $form['profile_researcher_profile']['field_user_institution'][LANGUAGE_NONE][0]['value']['#default_value'] = $user_data->institution;
          $form['profile_researcher_profile']['field_user_department'][LANGUAGE_NONE][0]['value']['#default_value'] = $user_data->department;
          $form['profile_researcher_profile']['field_user_position'][LANGUAGE_NONE][0]['value']['#default_value'] = $user_data->position;
          $form['profile_researcher_profile']['field_user_phone'][LANGUAGE_NONE][0]['value']['#default_value'] = $user_data->phone;
          $form['profile_researcher_profile']['field_user_address'][LANGUAGE_NONE][0]['value']['#default_value'] = $user_data->address;
          $form['profile_researcher_profile']['field_user_altemail'][LANGUAGE_NONE][0]['value']['#default_value'] = $user_data->altEmail;
        }
        else {
          // Problem with return json or conversion. Log and Notify.
          watchdog('nesi_user', 'REST response issue - check json for compliance.', NULL , WATCHDOG_CRITICAL, $link = NULL);
        }
      }
      else {
        // Need to handle this: 
        // Decision has been made to prevent access to account if REST connection fails. (as of 02082012).
        dpm('It appears that there may have been a problem querying the user in GOLD.');

        // If http response failure, add to watchdog and notify admin
      }
    } 
  }
}

/**
 * Implements hook_user_insert()
 */
function nesi_user_user_insert(&$edit, $account, $category) {  

  // Currently there are two registration options
  // With Tuakiri and without.
  // If profile_researcher_profile is correct, then user has registered manually
  if (isset($account->profile_researcher_profile)) {
    //dpm(' * Implements hook_user_insert()');
    //dpm($account);
    // Prepare user information for goldwrap
    $user_data = array();
    $user_data['userId'] = 'tuakiri-test-hash-'.$account->uid;
    $user_data['email'] = $account->mail;
    $user_data['firstName'] = $account->profile_researcher_profile['field_user_firstname'][LANGUAGE_NONE][0]['value'];
    $user_data['middleName'] = $account->profile_researcher_profile['field_user_middlename'][LANGUAGE_NONE][0]['value'];
    $user_data['lastName'] = $account->profile_researcher_profile['field_user_lastname'][LANGUAGE_NONE][0]['value'];
    $user_data['institution'] = $account->profile_researcher_profile['field_user_institution'][LANGUAGE_NONE][0]['value'];
    $user_data['department'] = $account->profile_researcher_profile['field_user_department'][LANGUAGE_NONE][0]['value'];
    $user_data['position'] = $account->profile_researcher_profile['field_user_position'][LANGUAGE_NONE][0]['value'];
    $user_data['phone'] = $account->profile_researcher_profile['field_user_phone'][LANGUAGE_NONE][0]['value'];
    $user_data['address'] = $account->profile_researcher_profile['field_user_address'][LANGUAGE_NONE][0]['value'];
    $user_data['altEmail'] = $account->profile_researcher_profile['field_user_altemail'][LANGUAGE_NONE][0]['value'];
    $user_data['nationality'] = $account->profile_researcher_profile['field_user_nationality'][LANGUAGE_NONE][0]['iso2'];
    //dpm($user_data);

    //$json_data = json_encode($user_data);
    //dpm($json_data);  

    // Attempt to connect to REST and create account
    $rest_result = nesi_rest_insert_user($user_data);  

    // Check for error or http response
    if ($rest_result <> FALSE) {
      //dpm('User was created successfully in GOLD.');
      //dpm($rest_result);
      watchdog('nesi_user', 'REST user created - UID " '.$user_data['userId'].' " ', NULL , WATCHDOG_ERROR, $link = NULL);
    }
    else {
      watchdog('nesi_user', 'REST create user failure - UID " '.$user_data['userId'].' " ', NULL , WATCHDOG_ERROR, $link = NULL);

      // Need to handle this: 
      // Decision has been made to prevent account registration if REST connection fails. (as of 02082012).
      // Multiple options to resolve this.
      // Initially, problem accounts will be created in Drupal for logging purposes but set to inactive.
      // User email will be altered to ensure that user can re-register. 
      // User will be notified and redirected to try re-register again later.
      // Need to prepare config so NeSI can manage all end-user response text.
      dpm('It appears that there may have been a problem creating the user in GOLD.');

      // If http response failure, add to watchdog and notify admin
    }
  }
  else {
    // No researcher profile exists, so this is an automated registration via Tuakiri
    // Process Tuakiri variables...
    dpm($_SERVER);
    dpm($_SESSION);   
 
  }
}

/**
 * Implements hook_user_update()
 */
function nesi_user_user_update(&$edit, $account, $category) {
  dpm('* Implements hook_user_update()');
  dpm($edit);
  dpm($category);

  if ($category == 'researcher_profile') {
    if ($account->uid > 1) {
    
      $user_data = array();
      $user_data['userId'] = 'tuakiri-test-hash-'.$account->uid;
      $user_data['email'] = $account->mail;
      $user_data['firstName'] = $edit['profile_researcher_profile']['field_user_firstname'][LANGUAGE_NONE][0]['value'];
      $user_data['middleName'] = $edit['profile_researcher_profile']['field_user_middlename'][LANGUAGE_NONE][0]['value'];
      $user_data['lastName'] = $edit['profile_researcher_profile']['field_user_lastname'][LANGUAGE_NONE][0]['value'];
      $user_data['institution'] = $edit['profile_researcher_profile']['field_user_institution'][LANGUAGE_NONE][0]['value'];
      $user_data['department'] = $edit['profile_researcher_profile']['field_user_department'][LANGUAGE_NONE][0]['value'];
      $user_data['position'] = $edit['profile_researcher_profile']['field_user_position'][LANGUAGE_NONE][0]['value'];
      $user_data['phone'] = $edit['profile_researcher_profile']['field_user_phone'][LANGUAGE_NONE][0]['value'];
      $user_data['address'] = $edit['profile_researcher_profile']['field_user_address'][LANGUAGE_NONE][0]['value'];
      $user_data['altEmail'] = $edit['profile_researcher_profile']['field_user_altemail'][LANGUAGE_NONE][0]['value'];
      $user_data['nationality'] = $edit['profile_researcher_profile']['field_user_nationality'][LANGUAGE_NONE][0]['iso2'];  

      dpm($user_data);

      //$json_data = json_encode($user_data);
      //dpm($json_data);  

      // Attempt to connect to REST and create account
      $rest_result = nesi_rest_update_user($user_data);  

      // Check for error or http response
      if ($rest_result <> FALSE) {
        //dpm('User was updated successfully in GOLD.');
        //dpm($rest_result);
        watchdog('nesi_user', 'REST user updated - UID " '.$user_data['userId'].' " ', NULL , WATCHDOG_ERROR, $link = NULL);
      }
      else {
        // If http response failure, add to watchdog and notify admin
        watchdog('nesi_user', 'REST update user failure - UID " '.$user_data['userId'].' " ', NULL , WATCHDOG_ERROR, $link = NULL);

        dpm('It appears that there may have been a problem updating the user in GOLD.');
      }
    }
  }
}

/**
 * Implements hook_user_view()
 */
function nesi_user_user_view($account, $view_mode, $langcode) {

  //dpm(' * Implements hook_user_view() ');
  //dpm($account);

  // Exclude superadmin
  if ($account->uid > 1) {

    $obj = entity_metadata_wrapper('user', $account);
    //dpm($obj->getPropertyInfo());
    
    if (!empty( $obj->profile_researcher_profile->value()->pid )) { 
   
      $profile = entity_metadata_wrapper ('profile2', $obj->profile_researcher_profile->value()->pid );
      //dpm ($profile->getPropertyInfo());
      //$test = $profile->field_user_firstname->value();

      /* Alternate data access method using field_get_items() will have to be used in some cases. */  
      //$profile_data = profile2_load_by_user($account->uid);
      //dpm($profile_data);
      //$test_get_profile = field_get_items('profile2', $profile_data['researcher_profile'], 'field_user_nationality');
      //dpm($test_get_profile);

      // Update view using nesi_rest
      //$profile->field_user_address->set('TestN'); 

      // Attempt to connect to REST and retrieve account information
      $rest_user_id = 'tuakiri-test-hash-'.$account->uid;
    
      $rest_result = nesi_rest_get_user($rest_user_id);  

      // Check for error or http response
      if ($rest_result <> FALSE) {
        dpm('User was successfully retrieved from GOLD.');
        dpm($rest_result);
        // Display nesi_rest data instead of Drupal data... (GOLD is considered "up to date")
        
        // Convert from json
        $user_data = json_decode($rest_result['json_data']);
        
        if ($user_data) {
          //dpm($user_data);

          $profile->field_user_firstname->set($user_data->firstName); 
          $profile->field_user_middlename->set($user_data->middleName); 
          $profile->field_user_lastname->set($user_data->lastName); 
          $profile->field_user_institution->set($user_data->institution); 
          $profile->field_user_department->set($user_data->department); 
          $profile->field_user_phone->set($user_data->phone); 
          $profile->field_user_position->set($user_data->position); 
          $profile->field_user_address->set($user_data->address); 
          $profile->field_user_altemail->set($user_data->altEmail); 
         // $profile->field_user_nationality->set('TestN'); 
        }
        else {
          // Problem with return json or conversion. Log and Notify.
          watchdog('nesi_user', 'REST response issue - check json for compliance.', NULL , WATCHDOG_CRITICAL, $link = NULL);
        }

      }
      else {

        // Need to handle this: 
        // Decision has been made to prevent access to account if REST connection fails. (as of 02082012).
        dpm('It appears that there may have been a problem querying the user in GOLD.');

        // If http response failure, add to watchdog and notify admin
      }
    }
  }
}

function nesi_user_username_alter(&$name, $account) {

  if ($account->uid > 1) {
    // Display actual user name rather than generated username
    if (!empty($_SERVER['Shib-Identity-Provider'])) {
      if (!empty($_SERVER['Shib-Identity-Provider'])) {
        $name = $_SERVER['displayName'];
      }
      else {
        // Tuakiri displayName not set. Curious detail, needs to be logged.
        watchdog('nesi_user', 'Tuakiri displayName is empty - UID " '.$account->uid.' " ', NULL , WATCHDOG_WARNING, $link = NULL);
      }
    }
    else {
      // Attempt to use researcher profile for non Tuakiri users
      $profile = profile2_load_by_user($account, 'researcher_profile');

      if (is_object($profile)) {
        $profile_data = entity_metadata_wrapper('profile2', $profile); 
        $name = $profile_data->field_user_firstname->value().' '.$profile_data->field_user_lastname->value();
      }
    }
  }
}

/**
 * Implements hook_user_view_alter()
 */
function nesi_user_user_view_alter(&$build) {
  //dpm('* Implements hook_user_view_alter()');
  //dpm($build);
}

/**
 * Implements hook_user_delete()
 */
function nesi_user_user_delete($account) {

  // DELETE disabled currently. 
  // Questions:
  // 1. Will portal be used to manage users (ie. remove them from GOLD?)
  // 2. Should user be able to delete own account?  
}

/**
 * Implements hook_user_login()
 */
function nesi_user_user_login(&$edit, $account) {
  
  // NOT YET IMPLEMENTED 
  // - Placeholder to bootstrap any required user login operations

}

