<?php
/**
 * @file
 * NeSI HPC Calculator module.
 *
 * @todo Add terms of service
 */

include_once 'includes/nesi_hpc_calc.forms.inc';

function nesi_hpc_calc_menu() {
	$items['hpc-calc'] = array(
			'title' => 'HPC Calculator',
			'page callback' => 'nesi_hpc_calc_page',
			'access callback' => TRUE,
	);
	return $items;
}

function nesi_hpc_calc_help($path, $arg) {
	switch ($path) {
		case "admin/help#nesi_hpc_calc":
			return '<p>'. t("NeSI HPC Calculator") .'</p>';
			break;
	}
}

/**
 * Render the form.
 * @param string $platform Platform
 * @param array $form Form to be rendered
 * @return string
 */
// TODO: The rendering is perhaps a bit crude.
// TODO: Add functionality to send calculation results as an e-mail
function render_form($form, $platform) {
	drupal_add_css(drupal_get_path('module', 'nesi_hpc_calc') .'/stylesheets/hpc_calc.css');
	$output = drupal_render($form[$platform.'_job_size']) . 
		'<div class="myerror">' . drupal_render($form[$platform.'_job_size_error']) . '</div>' . 
		'<hr>';
	if ($platform != "bluegene") {
		$output .= 	'<div id="' . $platform. '_override_allocation"><p/>' .
			'<b>' . drupal_render($form[$platform.'_override_allocation']) . '</b>' .
			'<table class="hpc_calc"><tr><td class="hpc_calc" width="40%">' .
			drupal_render($form[$platform.'_usage']) .
			'<div class="hpc_calc_inline">' .
			drupal_render($form[$platform.'_cpu_cores']) .
			drupal_render($form[$platform.'_cpu_cores_description']) .
			'<div class="myerror">' . drupal_render($form[$platform.'_cpu_cores_error']) . '</div>' .
			'</div>' .
    		'</td><td class="hpc_calc">' .
    		drupal_render($form[$platform.'_tip_01']) .
    		'</td></tr></table>' .
    		'<hr></div>';
	}
	$output .= drupal_render($form[$platform.'_cpu_cores_avail']) .
		'<table class="hpc_calc"><tr><td class="hpc_calc">' .
		drupal_render($form[$platform.'_wall_clock_hours']) .
		'<div class="myerror">' . drupal_render($form[$platform.'_wall_clock_hours_error']) . '</div>' .
		'</td><td class="hpc_calc">' . 
		drupal_render($form[$platform.'_number_job_runs']) .
		'<div class="myerror">' . drupal_render($form[$platform.'_number_job_runs_error']) . '</div>' .
		'</td></tr></table>' .
		'<hr>' .
		'<p/>' .
		'<table class="hpc_calc"><tr><td class="hpc_calc" width="60%">' .
		'<div class="hpc_calc_inline">' .
		'<b>' . drupal_render($form[$platform.'_core_cpu_hours_label']) . '</b>: ' .
		drupal_render($form[$platform.'_core_cpu_hours_value']) . '<br>' .
		'(' .drupal_render($form[$platform.'_core_cpu_hours_tip']) . ')' .
		'</div>' .
		'<p/>' .
		'</td><td class="hpc_calc">' . 
		'<div class="hpc_calc_inline">' .
		'<b>' . drupal_render($form[$platform.'_hpc_cost_label']) . '</b>: $' .
		drupal_render($form[$platform.'_hpc_cost_value']) . '<br>' .
		'(CPU core hours x ' . drupal_render($form[$platform.'_price_per_core_hour']) . ')' .
		'</div>' .
		'</td></tr></table>' .
		'<hr>' .
		'<p/>' .
		'<div class="hpc_calc_inline">' .
		'<b>' . drupal_render($form[$platform.'_project_cost_label']) . '</b>: $' .
		drupal_render($form[$platform.'_project_cost_value']) .
		'</div>' .
		'<p/>' .
		'<div class="hpc_calc_inline">' .
		'<b>' . drupal_render($form[$platform.'_nesi_contrib_label']) . '</b>: $' .
		drupal_render($form[$platform.'_nesi_contrib_value']) .
		'</div>';
	return $output;
}

function nesi_hpc_calc_page() {

	$module_path = drupal_get_path('module', 'nesi_hpc_calc');
	// Tabs are created using jquery-ui
	drupal_add_library('system', 'ui.tabs');
	drupal_add_js($module_path . '/javascripts/hpc_calc.js', 'file');
    $info_img = $module_path . '/images/info_small.png';
    include_once 'includes/tooltips.inc';    

	// Create tabs
    $output = '<div id="tabs">
	  <ul>
		<li id="power6_tab"><a href="#tab01"><div class="hpc_calc_tabheader_center"><b>POWER6</b><br>
		    <div class="hpc_calc_tabheader_smaller_font">$0.20 per CPU core hour<br>32 CPU cores/node</div>
		    <div class="hpc_calc_tabheader_right"><img id="power6_info" title="'.$power6_tooltip.'" src="'.$info_img.'"/></div>
		    </div></a>
		</li>
		<li id="power7_tab"><a href="#tab02"><div class="hpc_calc_tabheader_center"><b>POWER7</b><br>
		    <div class="hpc_calc_tabheader_smaller_font">$0.20 per CPU core hour<br>32 CPU cores/node</div>
		    <div class="hpc_calc_tabheader_right"><img id="power7_info" title="'.$power7_tooltip.'" src="'.$info_img.'"/></div>
		    </div></a>
		</li>
		<li id="intel_tab"><a href="#tab03"><div class="hpc_calc_tabheader_center"><b>Intel Cluster</b><br>
		    <div class="hpc_calc_tabheader_smaller_font">$0.20 per CPU core hour<br>12 CPU cores/node</div>
		    <div class="hpc_calc_tabheader_right"><img id="intel_info" title="'.$intel_tooltip.'" src="'.$info_img.'"/></div>
		    </div></a>
		</li>
		<li id="bluegene_tab"><a href="#tab04"><div class="hpc_calc_tabheader_center"><b>BlueGene/P</b><br>
		    <div class="hpc_calc_tabheader_smaller_font">$0.05 per CPU core hour<br>256 CPU cores/partition</div>
		    <div class="hpc_calc_tabheader_right"><img id="bluegene_info" title="'.$bluegene_tooltip.'" src="'.$info_img.'"/></div>
		    </div></a>
		</li>
	  </ul>';
    // Create content for the tabs
    $output .= 
      	'<div id="tab01">' . render_form(drupal_get_form('hpc_create_power6_form'), 'power6') . '</div>' .
		'<div id="tab02">' . render_form(drupal_get_form('hpc_create_power7_form'), 'power7') . '</div>' .
		'<div id="tab03">' . render_form(drupal_get_form('hpc_create_intel_form'), 'intel') . '</div>' .
		'<div id="tab04">' . render_form(drupal_get_form('hpc_create_bluegene_form'), 'bluegene') . '</div>' .
		'</div>';
	return $output;
}
