<?php
/**
 * @file
 * NeSI HPC Calculator module.
 *
 * @todo Add terms of service
 */

include_once 'includes/nesi_hpc_calc.forms.inc';

function nesi_hpc_calc_menu() {
	$items['hpc-calc'] = array(
			'title' => 'HPC Calculator',
			'page callback' => 'nesi_hpc_calc_page',
			'access callback' => TRUE,
	);
	return $items;
}

function nesi_hpc_calc_help($path, $arg) {
	switch ($path) {
		case "admin/help#nesi_hpc_calc":
			return '<p>'. t("NeSI HPC Calculator") .'</p>';
			break;
	}
}

/**
 * Render the form.
 * @param string $platform Platform
 * @param array $form Form to be rendered
 * @return string
 */
// TODO: The rendering is perhaps a bit crude.
// TODO: Add functionality to send calculation results as an e-mail
function render_form($form, $platform) {
	drupal_add_css(drupal_get_path('module', 'nesi_hpc_calc') .'/stylesheets/hpc_calc.css');
	drupal_add_css(drupal_get_path('module', 'nesi_hpc_calc') .'/stylesheets/jquery.qtip.css');
	$output = '<table class="hpc_calc"><tr><td class="hpc_calc">' .
		drupal_render($form[$platform.'_job_size_title']) .
		'<div class="hpc_calc_inline">' .
		drupal_render($form[$platform.'_job_size']) . 
		'<span class="hpc_calc_description">' .
		drupal_render($form[$platform.'_job_size_description']) . 
		'</span>' .
		'</div>' .
		'<div class="myerror">' . drupal_render($form[$platform.'_job_size_error']) . '</div>' . 
		'</td><td class="hpc_calc">' .
		drupal_render($form[$platform.'_wall_clock_hours_title']) .
		'<div class="hpc_calc_inline">' .
		drupal_render($form[$platform.'_wall_clock_hours']) .
		'<span class="hpc_calc_description">' .
		drupal_render($form[$platform.'_wall_clock_hours_description']) .
		'</span>' .
		'</div>' . 
		'<div class="myerror">' . drupal_render($form[$platform.'_wall_clock_hours_error']) . '</div>' .
		'</td></tr></table>' .
		'<hr>';
	if ($platform != "bluegene") {
		$output .=
			'<div id="' . $platform. '_usage">' .
			drupal_render($form[$platform.'_usage_title']) .
			drupal_render($form[$platform.'_usage']) .
			'<div class="hpc_calc_inline">' .
			drupal_render($form[$platform.'_cpu_cores_per_node_title']) .
			drupal_render($form[$platform.'_cpu_cores_per_node']) .
			drupal_render($form[$platform.'_cpu_cores_per_node_description']) .
			'<div class="myerror">' . drupal_render($form[$platform.'_cpu_cores_per_node_error']) . '</div>' .
			'</div>' .
    		drupal_render($form[$platform.'_usage_description']) .
    		'<hr></div>';
	}
	
	$output .= drupal_render($form[$platform.'_cpu_cores_avail']);
	$output .= drupal_render($form[$platform.'_price_per_core_hour']);
	
	$output .=
		drupal_render($form[$platform.'_number_job_runs_title']) .
		drupal_render($form[$platform.'_number_job_runs']) .
		'<div class="myerror">' . drupal_render($form[$platform.'_number_job_runs_error']) . '</div>' .
		'<hr>';
	
	$output .=
		'<table class="hpc_calc"><tr><td width="70%" class="hpc_calc">' .
		drupal_render($form[$platform.'_cpu_core_hours_title']) . '<br>' .
		'<span class="hpc_calc_description">' .
		drupal_render($form[$platform.'_cpu_core_hours_description']) .
		'</span>' .
		'</td><td class="hpc_calc_right">' .
		drupal_render($form[$platform.'_cpu_core_hours']) .
		'</td></tr></table>';
		
	$output .= 
		'<table class="hpc_calc"><tr><td width="70%" class="hpc_calc">' .
		drupal_render($form[$platform.'_hpc_cost_title']) . '<br>' .
		'<span class="hpc_calc_description">' .
		drupal_render($form[$platform.'_hpc_cost_description']) .	
		'</span>' .
		'</td><td class="hpc_calc_right">' .
		drupal_render($form[$platform.'_hpc_cost']) .
		'</td></tr></table>' .
		'<hr>';
	
	$output .=
		'<table class="hpc_calc"><tr><td width="70%" class="hpc_calc">' .
		drupal_render($form[$platform.'_project_cost_title']) .
		'</td><td class="hpc_calc_right">' .
		drupal_render($form[$platform.'_project_cost']) .
		'</td></tr></table>';
			
	$output .=
		'<table class="hpc_calc"><tr><td width="70%" class="hpc_calc">' .
		drupal_render($form[$platform.'_nesi_contribution_title']) .
		'</td><td class="hpc_calc_right">' .
		drupal_render($form[$platform.'_nesi_contribution']) .
		'</td></tr></table>';
	
	return $output;
}

function nesi_hpc_calc_page() {

	$module_path = drupal_get_path('module', 'nesi_hpc_calc');
	// Tabs are created using jquery-ui
	drupal_add_library('system', 'ui.tabs');
	drupal_add_js($module_path . '/javascripts/hpc_calc.js', 'file');
	drupal_add_js($module_path . '/javascripts/jquery.qtip-1.0.0-rc3.min.js');
	$info_img = $module_path . '/images/info_small.png';
    include_once 'includes/tooltips.inc';    

	// Create tabs
    $output = '<div id="tabs">
	  <ul>
		<li id="power6_tab"><a href="#tab01"><div class="hpc_calc_tabheader_center"><b>POWER6</b><br>
		    <div class="hpc_calc_tabheader_smaller_font">$0.20 per CPU core hour</div>
		    <div class="hpc_calc_tabheader_right"><img id="power6_info" title="'.$power6_tooltip.'" src="'.$info_img.'"/></div>
		    </div></a>
		</li>
		<li id="power7_tab"><a href="#tab02"><div class="hpc_calc_tabheader_center"><b>POWER7</b><br>
		    <div class="hpc_calc_tabheader_smaller_font">$0.20 per CPU core hour</div>
		    <div class="hpc_calc_tabheader_right"><img id="power7_info" title="'.$power7_tooltip.'" src="'.$info_img.'"/></div>
		    </div></a>
		</li>
		<li id="intel_tab"><a href="#tab03"><div class="hpc_calc_tabheader_center"><b>Intel Cluster</b><br>
		    <div class="hpc_calc_tabheader_smaller_font">$0.20 per CPU core hour</div>
		    <div class="hpc_calc_tabheader_right"><img id="intel_info" title="'.$intel_tooltip.'" src="'.$info_img.'"/></div>
		    </div></a>
		</li>
		<li id="bluegene_tab"><a href="#tab04"><div class="hpc_calc_tabheader_center"><b>BlueGene/P</b><br>
		    <div class="hpc_calc_tabheader_smaller_font">$0.05 per CPU core hour</div>
		    <div class="hpc_calc_tabheader_right"><img id="bluegene_info" title="'.$bluegene_tooltip.'" src="'.$info_img.'"/></div>
		    </div></a>
		</li>
	  </ul>';
    // Create content for the tabs
    $output .= 
      	'<div id="tab01">' . render_form(drupal_get_form('hpc_create_power6_form'), 'power6') . '</div>' .
		'<div id="tab02">' . render_form(drupal_get_form('hpc_create_power7_form'), 'power7') . '</div>' .
		'<div id="tab03">' . render_form(drupal_get_form('hpc_create_intel_form'), 'intel') . '</div>' .
		'<div id="tab04">' . render_form(drupal_get_form('hpc_create_bluegene_form'), 'bluegene') . '</div>' .
		'</div>';
	return $output;
}
