<?php
/**
 * @file
 * Code for the NeSI Project feature.
 */

include_once 'nesi_project.features.inc';

function nesi_project_node_access($node, $op, $account) {
// Limit access to proposal once submitted..
  global $user;

  if ($op == 'view') {
    if (($node->type == 'project')) {
      // Block anonymous
      if ($user->uid < 1) {
        return NODE_ACCESS_DENY;
      }
      // Check for ownership or appropriate role
      if ($user->uid != $node->uid) {
        // Otherwise check if user has appropriate role 
        if (!in_array('reviewer', array_values($account->roles))) {
          // Otherwise check if user included within Team 
          $user_check = _nesi_team_selector_uid_search($user->uid, $node->field_p_teamlist[LANGUAGE_NONE]);
          if ($user_check === FALSE) {
            return NODE_ACCESS_DENY;
          }
        }
      }
    }
  }
}
