<?php
/**
 * @file
 * NeSI Project module - installation.
 * 
 * This file is executed on installation of the nesi_project module.
 *
 */

/**
 * Implements hook_project_install()
 */
function nesi_project_install() {

  /* Current actions on install:
   * Set URI pattern for researcher project
   */

  /* Set default URI pattern */
  variable_set( 'pathauto_node_project_pattern', 'researcher/project/[node:nid]' );

}

