<?php
/**
 * @file
 * NeSI Portal module.
 * 
 * The purpose of this module is to temporarily provide configuration and settings for the NeSI portal.
 * The module may be removed as the build process is further developed. 
 *
 */

function nesi_portal_menu_alter(&$items) {

  //global $user;
  //dpm($user);

  //if (in_array("researcher", $user->roles)) { 
  $items['node/add']['title'] = 'Add Proposal';
  //}
  //if (in_array("administrator", $user->roles)) { 
  //  $items['node/add']['title'] = 'Add Proposal/Content';
  //}
}
