<?php
/**
 * @file
 * NeSI HPC Calculator module.
 *
 */

include_once 'includes/nesi_hpc_calc.forms.inc';

function nesi_hpc_calc_menu() {
	$items['hpc-calculator'] = array(
			'title' => 'HPC Calculator',
			'page callback' => 'nesi_hpc_calc_page',
			'access callback' => TRUE,
	);
	return $items;
}

function nesi_hpc_calc_help($path, $arg) {
	switch ($path) {
		case "admin/help#nesi_hpc_calc":
			return '<p>'. t("NeSI HPC Calculator") .'</p>';
			break;
	}
}

/**
 * Render the form.
 * @param string $platform Platform
 * @param array $form Form to be rendered
 * @return string
 */
// TODO: The rendering is perhaps a bit crude.
// TODO: Add functionality to send calculation results as an e-mail
function render_form($form, $platform, $tooltips) {
	drupal_add_css(drupal_get_path('module', 'nesi_hpc_calc') .'/stylesheets/hpc_calc.css');
	drupal_add_css(drupal_get_path('module', 'nesi_hpc_calc') .'/stylesheets/jquery.qtip.css');
	include_once 'includes/tooltips.inc';
	
	$output = '<fieldset><div class="hpc_calc_inline">' .
		'<label>' . 
		drupal_render($form[$platform.'_job_size_title']) .
		$tooltips['job_size'] .
		'</label>' .
		drupal_render($form[$platform.'_job_size']) . 
		'<span class="add-on">' .
		drupal_render($form[$platform.'_job_size_description']) . 
		'</span>' .
		'</div>' .
		'<div class="myerror">' . drupal_render($form[$platform.'_job_size_error']) . '</div>' . 
		'<div class="hpc_calc_inline">' .
		'<label>' . 
		drupal_render($form[$platform.'_wall_clock_hours_title']) .
		$tooltips['wall_clock_hours'] .
		'</label>' .
		drupal_render($form[$platform.'_wall_clock_hours']) .
		'<span class="add-on">' .
		drupal_render($form[$platform.'_wall_clock_hours_description']) .
		'</span>' .
		'</div>' . 
		'<div class="myerror">' . drupal_render($form[$platform.'_wall_clock_hours_error']) . '</div>' .
		'</fieldset>';
	if ($platform != "bluegene") {
		$output .=
			'<fieldset id="' . $platform. '_usage">' .
			'<table class="hpc_calc"><tr><td class="hpc_calc">' .
			'<legend>' . drupal_render($form[$platform.'_usage_title']) . '</legend>' .
			'</td><td class="hpc_calc_right">' .
			'<div class="hpc_calc_inline">' .
			drupal_render($form[$platform.'_job_efficiency_title']) .
			drupal_render($form[$platform.'_job_efficiency']) .
			'</div>' .
			'</td></tr></table>' .
			drupal_render($form[$platform.'_usage']) .
			'<div class="hpc_calc_inline">' .
			drupal_render($form[$platform.'_cpu_cores_per_node_title']) .
			drupal_render($form[$platform.'_cpu_cores_per_node']) .
			drupal_render($form[$platform.'_cpu_cores_per_node_description']) .
			'<div class="myerror">' . drupal_render($form[$platform.'_cpu_cores_per_node_error']) . '</div>' .
			'</div>' .
    		drupal_render($form[$platform.'_usage_description']) .
    		'<hr></fieldset>';
	}
	
	$output .= drupal_render($form[$platform.'_cpu_cores_avail']);
	$output .= drupal_render($form[$platform.'_price_per_core_hour']);
	
	$output .=
		'<label>' .
		drupal_render($form[$platform.'_number_job_runs_title']) .
    '<i class="icon-question-sign" data-content="How many times your job needs to run." rel="popover" data-original-title=""></i>' .
		'</label>' .
		drupal_render($form[$platform.'_number_job_runs']) .
		'<div class="myerror">' . drupal_render($form[$platform.'_number_job_runs_error']) . '</div>' .
		'<hr>';
	
	$output .=
		'<table class="hpc_calc"><tr><td width="70%" class="hpc_calc">' .
		drupal_render($form[$platform.'_cpu_core_hours_title']) . '<br>' .
		'<span class="hpc_calc_description">' .
		drupal_render($form[$platform.'_cpu_core_hours_description']) .
		'</span>' .
		'</td><td class="hpc_calc_right"><b>' .
		drupal_render($form[$platform.'_cpu_core_hours']) .
		'</b></td></tr></table>';
		
	$output .= 
		'<table class="hpc_calc"><tr><td width="70%" class="hpc_calc">' .
		drupal_render($form[$platform.'_hpc_cost_title']) . '<br>' .
		'<span class="hpc_calc_description">' .
		drupal_render($form[$platform.'_hpc_cost_description']) .	
		'</span>' .
		'</td><td class="hpc_calc_right"><b>' .
		drupal_render($form[$platform.'_hpc_cost']) .
		'</b></td></tr></table>' .
		'<hr>';
	
	$output .=
		'<table class="hpc_calc"><tr><td width="70%" class="hpc_calc">' .
		drupal_render($form[$platform.'_project_cost_title']) .
		'</td><td class="hpc_calc_right"><b>' .
		drupal_render($form[$platform.'_project_cost']) .
		'</b></td></tr></table>';
			
	$output .=
		'<table class="hpc_calc"><tr><td width="70%" class="hpc_calc">' .
		drupal_render($form[$platform.'_nesi_contribution_title']) .
		'</td><td class="hpc_calc_right"><b>' .
		drupal_render($form[$platform.'_nesi_contribution']) .
		'</b></td></tr></table>';
	
	return $output;
}

function nesi_hpc_calc_page() {

	$module_path = drupal_get_path('module', 'nesi_hpc_calc');
	// Tabs are created using jquery-ui
	drupal_add_js($module_path . '/javascripts/hpc_calc.js', 'file');
	drupal_add_js($module_path . '/javascripts/jquery.qtip-1.0.0-rc3.min.js');
	$info_img = $module_path . '/images/info_small.png';
    include_once 'includes/tooltips.inc';    

	// Create tabs
  $output = '<div id="hpc-calculator" class="content">
	  <ul class="nav nav-tabs">
		<li id="power6_tab" class="active"><a data-toggle="tab" href="#tab01">POWER6
		    <span>$0.20 per CPU core hour</span></a>
		    <i id="power6_platform_info" class="icon-info-sign">info on this platform</i>
		</li>
		<li id="power7_tab"><a data-toggle="tab" href="#tab02">POWER7
		    <span>$0.20 per CPU core hour</span></a>
		    <i id="power7_platform_info" class="icon-info-sign">info on this platform</i>
		</li>
		<li id="intel_tab"><a data-toggle="tab" href="#tab03">Intel Cluster
		    <span>$0.20 per CPU core hour</span></a>
		    <i id="intel_platform_info" class="icon-info-sign">info on this platform</i>
		</li>
		<li id="bluegene_tab"><a data-toggle="tab" href="#tab04">BlueGene/P
		    <span>$0.05 per CPU core hour</span></a>
		    <i id="bluegene_platform_info" class="icon-info-sign">info on this platform</i>
		</li>
	  </ul>';
    // Create content for the tabs
    $output .= 
    '<div class="tab-content"><div id="tab01" class="tab-pane fade active in"><aside id="power6_platform_detail">'.$tooltips['power6'].'</aside><div class="platform_form">' . render_form(drupal_get_form('hpc_create_power6_form'), 'power6', $tooltips) . '</div></div>' .
		'<div id="tab02" class="tab-pane fade"><aside id="power7_platform_detail">'.$tooltips['power7'].'</aside><div class="platform_form">' . render_form(drupal_get_form('hpc_create_power7_form'), 'power7', $tooltips) . '</div></div>' .
		'<div id="tab03" class="tab-pane fade"><aside id="intel_platform_detail">'.$tooltips['intel'].'</aside><div class="platform_form">' . render_form(drupal_get_form('hpc_create_intel_form'), 'intel', $tooltips) . '</div></div>' .
		'<div id="tab04" class="tab-pane fade"><aside id="bluegene_platform_detail">'.$tooltips['bluegene'].'</aside><div class="platform_form">' . render_form(drupal_get_form('hpc_create_bluegene_form'), 'bluegene', $tooltips) . '</div></div>' .
		'</div></div>';
	return $output;
}
