<?php

/**
 * Tooltips for the Tabs
 */

// TODO: What tool do we use for HTML tooltips?
// TODO: Fill in content for tooltips for p7, intel, bluegene

$p6_tooltip = '<h3>NIWA P575/POWER6</h3>
<table>
<tr>
  <td><b>Hardware</b></td>
  <td><b>Operating Environment</b></td>
</tr>
<tr>
  <td>58 nodes each with 32 cores (1856 4.7 GHz processor cores) with 64 and 128 GB RAM nodes total 5376 GB RAM increasing to 108 nodes (3456 processor cores) total 8704 GB RAM from 2012
DDR Infiniband interconnect between nodes</td>
  <td>AIX<br>GPFS high performance parallel file system<br>LoadLeveler workload scheduler and TSM-SM Hierarchical Storage Management (HSM)</td>
</tr>
</table>
<b>Facility</b><br>
FitzRoy High Performance Computing Facility, NIWA';

$p7_tooltip = 'This is POWER7';

$intel_tooltip = 'This is Intel Cluster';

$bluegene_tooltip = 'This is BlueGene/P';
